proxy:
   build: .
   restart: always
   net: host
   # 代理说明: https://www.daozzg.com/2018/03/23/ssh-forward/
   command: sh -c ' ssh -o TCPKeepAlive=yes -o StrictHostKeyChecking=no -tt  root@217.69.3.11 -L 0.0.0.0:9011:127.0.0.1:9011 "while true ; do echo ok ;sleep 10; done" '
   volumes:
     -  /root/.ssh:/root/.ssh
