proxy:
   #build: .
   image: daocloud.io/zheng--guang/ssh
   restart: always
   net: host # 如果是mac，这里会不工作,请改用ports参数暴露代理的端口, https://forums.docker.com/t/should-docker-run-net-host-work/14215/29
#   ports: #仅当net:host 不工作时需要配置
#     - 9011:9011
   # 代理说明: https://www.daozzg.com/2018/03/23/ssh-forward/
   command: sh -c ' ssh -o TCPKeepAlive=yes -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -tt  root@217.69.3.11 -L 0.0.0.0:9011:127.0.0.1:9011 "while true ; do echo ok ;sleep 10; done" '
   volumes:
     -  /root/.ssh:/root/.ssh
